name: searchandstay
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.5
  get: 4.6.5
  get_storage: 2.1.1
  validatorless: 1.2.3
  google_fonts: 4.0.4
  device_preview: 1.1.0
  supabase_flutter: 1.8.1
  logger: 1.3.0
  flutter_dotenv: 5.0.2
  dio: 5.1.1
  flutter_launcher_icons: 0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: 2.2.19

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

flutter_native_splash:
  image: "assets/logo.png"
  color: '#FFFFFF'
